language: julia
os:
  - linux
julia:
  - nightly
notifications:
  email: false
before_install:
  - sudo apt-get -qq install gdb cmake libssh2-1-dev openssh-client openssh-server
script:
  - git submodule init
  - git submodule update
  # we need a global config for config tests
  - git config --global user.name "testfirst testlast" 
  - git config --global user.email "test@test.com"
  - julia -e 'Pkg.init(); 
              run(`ln -s $(pwd()) $(Pkg.dir("LibGit2"))`);
              Pkg.pin("LibGit2");
              Pkg.resolve();'
  - julia -e 'Pkg.build("LibGit2")'
  - julia -e 'using LibGit2; @assert isdefined(:LibGit2); @assert typeof(LibGit2) === Module'
  - cd test/
  - julia --code-coverage runtests.jl all
# - sh run_remote_clone.sh
after_success:
  - julia -e 'cd(Pkg.dir("LibGit2")); 
              Pkg.add("Coverage"); 
              using Coverage; 
              Coveralls.submit(Coveralls.process_folder())'
