environment:
  matrix:
  - JULIAVERSION: "win32"
  - JULIAVERSION: "win64"

install:
# Download most recent Julia Windows binary
  - ps: (new-object net.webclient).DownloadFile($("http://status.julialang.org/download/"+$env:JULIAVERSION), "C:\projects\julia-binary.exe")
# Run installer silently, output to C:\projects\julia
  - C:\projects\julia-binary.exe /S /D=C:\projects\julia

build_script:
# Need to convert from shallow to complete for Pkg.clone to work
  - IF EXIST .git\shallow (git fetch --unshallow)
  - C:\projects\julia\bin\julia -e "versioninfo(); 
                                    Pkg.init(); 
                                    Pkg.clone(pwd(), \"LibGit2\"); 
                                    Pkg.build(\"LibGit2\");
                                    cd(Pkg.dir(\"LibGit2\"));
                                    run(`git submodule init`);
                                    run(`git submodule update`);
                                    run(`git config --global user.name \"testfirst testlast\"`);
                                    run(`git config --global user.email \"test@test.com\"`)"
test_script:
  - C:\projects\julia\bin\julia -e "Pkg.test(\"LibGit2\")"
